name: Trigger auto deployment for api-lab

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '//**'
    - '.github/workflows/api-lab-AutoDeployTrigger-d68e8aa2-0925-4c51-849a-3e5414b03fb1.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.APILAB_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.APILAB_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.APILAB_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: containers0823.azurecr.io
          registryUsername: ${{ secrets.APILAB_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.APILAB_REGISTRY_PASSWORD }}
          containerAppName: api-lab
          resourceGroup: ContainerAppLab
          imageToBuild: containers0823.azurecr.io/api-lab:${{ github.sha }}
          dockerfilePath: Dockerfile


